
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "studentWS", targetNamespace = "http://ws.entite/", wsdlLocation = "http://localhost:8081/?wsdl")
public class StudentWS
    extends Service
{

    private static final URL STUDENTWS_WSDL_LOCATION;
    private static final WebServiceException STUDENTWS_EXCEPTION;
    private static final QName STUDENTWS_QNAME = new QName("http://ws.entite/", "studentWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTWS_WSDL_LOCATION = url;
        STUDENTWS_EXCEPTION = e;
    }

    public StudentWS() {
        super(__getWsdlLocation(), STUDENTWS_QNAME);
    }

    public StudentWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTWS_QNAME, features);
    }

    public StudentWS(URL wsdlLocation) {
        super(wsdlLocation, STUDENTWS_QNAME);
    }

    public StudentWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTWS_QNAME, features);
    }

    public StudentWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentWebService
     */
    @WebEndpoint(name = "StudentWebServicePort")
    public StudentWebService getStudentWebServicePort() {
        return super.getPort(new QName("http://ws.entite/", "StudentWebServicePort"), StudentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentWebService
     */
    @WebEndpoint(name = "StudentWebServicePort")
    public StudentWebService getStudentWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.entite/", "StudentWebServicePort"), StudentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTWS_EXCEPTION!= null) {
            throw STUDENTWS_EXCEPTION;
        }
        return STUDENTWS_WSDL_LOCATION;
    }

}
