
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "StudentWebService", targetNamespace = "http://ws.entite/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentWebService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://ws.entite/", className = "proxy.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://ws.entite/", className = "proxy.GetAllStudentsResponse")
    @Action(input = "http://ws.entite/StudentWebService/getAllStudentsRequest", output = "http://ws.entite/StudentWebService/getAllStudentsResponse")
    public List<Student> getAllStudents();

}
